# Generated by Django 5.2.4 on 2025-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Users that this user is following.', related_name='following_users', to='accounts.customuser'),
        ),
    ]
